version: 2
jobs:
  build:
    docker:
      - image: golang:1.14
    working_directory: /go/src/github.com/TicketsBot/worker

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Install czlib
          command: apt-get update; apt-get install -y zlib1g-dev

      - run:
          name: Build worker
          command: go build -o main cmd/worker/main.go

      - store_artifacts:
          path: /go/src/github.com/TicketsBot/worker/main
          destination: main